# Generated by Django 3.2.7 on 2022-01-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20220115_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
