# Generated by Django 3.2.7 on 2022-01-16 14:06

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20220116_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name=django.contrib.auth.models.User),
        ),
    ]
