# Generated by Django 3.2.7 on 2022-01-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_room_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
